hastexo/tutor-contrib-backup

tutorbackup/patches/k8s-jobs

* `affinity` does not belong in the `Job` or `CronJob` spec; it belongs in the template spec for the pod that the `Job` or `CronJob` starts.
* Any `CronJob`'s pod template spec needs a `restartPolicy` property.

fix: Correct CronJob definitions

---

.bumpversion.cfg
CHANGELOG.md
README.md

Now that we have working backup and restore functionality both locally and in Kubernetes, it's probably a good time to cut 0.0.1 before we add other bells and whistles.

build: Version 0.0.1

---

tutorbackup/patches/k8s-jobs
tutorbackup/plugin.py
tutorbackup/templates/backup/build/backup/Dockerfile
tutorbackup/templates/backup/build/backup/restore_services.py
tutorbackup/templates/backup/build/backup/s3_client.py

* Consolidate the restore Bash script and the S3 download Python script
  to a single Python script. This facilitates logging and testing.
* Check file integrity after downloading from S3. We cannot rely on
the 'ETag' property being the checksum, as we did in the upload
script. boto3 downloads the file in chunks and that will cause 'ETag'
to not match the checksum of the file. Instead, we compare the size
of the downloaded file with the one on S3 to have some sort of
integrity check.
* Raise a custom exception when file integrity could not be verified.
boto3's ClientError is not a static Python exception. We shouldn't
use it.

refactor: Replace restore shell script with Python

---

tutorbackup/templates/backup/build/backup/restore_services.py

Bu default `shutils.copytree` throws an exception if the Caddy data
directory (or any of its sub-directories) already exist.
Set `dirs_exist_ok = True` to overwrite the existing data directory.
Reference: https://docs.python.org/3.8/library/shutil.html#shutil.copytree

fix: Overwrite existing Caddy data when restoring

---

CHANGELOG.md
tutorbackup/templates/backup/build/backup/backup_services.py
tutorbackup/templates/backup/build/backup/restore_services.py

* When checking file integrity after download, compare the checksum to the correct version of the backup file on S3.
* Re-raise any exceptions that happen when interacting with S3 to stop the script at the correct place and provide better stack traces.

Fix restore integrity check

---

CHANGELOG.md
tutorbackup/templates/backup/build/backup/backup_services.py
tutorbackup/templates/backup/build/backup/restore_services.py

Format log messages to include timestamp and level to improve the
readability and usefulness of the logs.

feat: Add timestamps to log messages

---

CHANGELOG.md
tutorbackup/templates/backup/build/backup/restore_services.py

`boto3.client.head_object` will break if empty string or None values
are passed as the `VersionId` argument. So add that function argument
only if a version ID is given.

fix: Fix for k8s restore failing if no version ID is given

---

CHANGELOG.md
README.md
tutorbackup/plugin.py
tutorbackup/templates/backup/build/backup/restore_services.py

Add a `--list-versions` flag to k8s restore to list available
backup version IDs along with their timestamps. Note that since this
will start a Kubernetes Job, the output will be in the corresponding
pod's log.

feat: List available backup versions

---

README.md

Make it clear that the user needs to run `tutor config save` after
enabling the plugin. Otherwise, the build image step will fail due
to missing plugin configuration values.
This PR was prompted by [this discussion](https://discuss.overhang.io/t/introducing-the-backup-restore-plugin/2632/3) on Tutor community forum.

docs: Add `tutor config save` step under Usage

---

CHANGELOG.md
setup.py
tutorbackup/plugin.py

Tutor v1 plugin API was introduces in Tutor 13.2.0. Refactor the plugin
to use the v1 API instead of the legacy v0 API.
Reference: https://github.com/overhangio/cookiecutter-tutor-plugin#migrating-from-v0-plugins

refactor: Use Tutor v1 plugin API

---

CHANGELOG.md
README.md
tutorbackup/patches/k8s-jobs
tutorbackup/plugin.py

Previously we relied on the existence of the schedule configuration
parameters to add or remove the corresponding backup and restore
CronJob. But, if a CronJob is already defined, removing its manifest
does not deactivate it. To deactivate a CronJob we need to suspend it.
Add `BACKUP_K8S_CRONJOB_BACKUP_ENABLE` and
`BACKUP_K8S_CRONJOB_RESTORE_ENABLE` to set the `.spec.suspend` in the
CronJob manifest. We also need to set `.spec.startingDeadlineSeconds`
to prevent the missed jobs to be immediately scheduled when
`.spec.suspend` is toggled from `true` to `false`.
Reference:
https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/

feat: Add ability to enable and disable CronJobs

---

.bumpversion.cfg
CHANGELOG.md
README.md

#33 adds a new feature, so we want to bump the minor.
Also, add a changelog entry for #31, and a doc patch to address #32.

Prepare 0.2.0 release

---

CHANGELOG.md
README.md
tutorbackup/plugin.py
tutorbackup/templates/backup/build/backup/backup_services.py
tutorbackup/templates/backup/build/backup/restore_services.py

Users can now specify a date when using the restore command. In a
Kubernetes deployment, if multiple backups are made in one day, users
can specify the date and the version ID of the desired backup when
restoring.

feat: Add a date stamp to backup file names

---

.bumpversion.cfg
CHANGELOG.md
README.md

Since we are adding a new feature (date-stamped backups) from #35, bump the minor.
Also include a small update to the README that explicitly references the changelog.

Prepare 0.3.0 release

---

README.md

* Reformat the section on using `BACKUP_MYSQL_DATABASES` to include only certain databases in the backup. Move the inline note on AWS Aurora to a footnote.
* Remove the "experimental" warning from the README.

docs: Small README updates

---

CHANGELOG.md
README.md
tutorbackup/patches/k8s-jobs
tutorbackup/patches/local-docker-compose-jobs-services
tutorbackup/plugin.py
tutorbackup/templates/backup/build/backup/backup_services.py

Add the `BACKUP_MONGODB_DATABASES` setting to select the
MongoDB databases to back up. If this setting is not provided,
back up all databases.
Since we are providing the `--db` flag to `mongodump`, when backing
up specific databases, we need to also provide the authentication
database. Otherwise `mongodump` uses whatever database is set by `--db`
to authenticate. To give users the ability to specify the
authentication database, add `BACKUP_MONGODB_AUTHENTICATION_DATABASE`
which defaults to `admin`.
Fixes #46.

feat: Add ability to select MongoDB databases

---

CHANGELOG.md
README.md
tutorbackup/patches/k8s-jobs
tutorbackup/patches/local-docker-compose-jobs-services
tutorbackup/plugin.py
tutorbackup/templates/backup/build/backup/backup_services.py
tutorbackup/templates/backup/build/backup/restore_services.py

In K8s use ephemeral volumes for data and backup mount points.

fix: Use ephemeral volumes in K8s

---

CHANGELOG.md
tutorbackup/templates/backup/build/backup/backup_services.py
tutorbackup/templates/backup/build/backup/restore_services.py
tutorbackup/templates/backup/build/backup/s3_client.py

When calculating the checksum for large backup tar files, all the file was read into memory. This could cause pods to be killed when backing up large databases. Fix that by reading in the tar file in chunks when calculating the checksum.

fix: Make checksum calculation memory-efficient

---

CHANGELOG.md
README.md
tutorbackup/patches/k8s-jobs
tutorbackup/patches/local-docker-compose-jobs-services
tutorbackup/plugin.py
tutorbackup/templates/backup/build/backup/restore_services.py

Add BACKUP_MONGORESTORE_ADDITIONAL_OPTIONS setting (defaults to none) to add options to the mongorestore command. By default, mongorestore will attempt to restore four collections concurrently. This causes the process to consume a lot of memory and potentially break the process in low memory environments, specially in K8s deployments. Set BACKUP_MONGORESTORE_ADDITIONAL_OPTIONS to '-j 1' to reduce memory requirements by restoring one collection at a time. See [issue #54](https://github.com/hastexo/tutor-contrib-backup/issues/54) for more details.

feat: Add mongorestore additional options

---

.github/workflows/tox.yml
.gitlint

* Fix the GitHub Actions workflow so that it uses the latest releases and
lints the correct commit's commit message.
* Explicitly switch gitlint to regex "search" semantics

Update GitHub Actions, switch gitlint to regex "search" semantics

---

CHANGELOG.md
tutorbackup/patches/k8s-jobs

Commit 404068260ad709dadadf4d9477ec49fb1bfb8786 introduced `BACKUP_MONGORESTORE_ADDITIONAL_OPTIONS`, but only added it to the Kubernetes environment for the ad-hoc restore job. It failed to also set it for the corresponding cron job definition.
Add this environment variable to the definition of the cron job, as well.
Reference:
https://github.com/hastexo/tutor-contrib-backup/pull/55

fix: Set MONGORESTORE_ADDITIONAL_OPTIONS on cron job

---

CHANGELOG.md
README.md
setup.py
tutorbackup/templates/backup/build/backup/Dockerfile

Bring things in line with Tutor itself: 
* Use an Ubuntu base image instead of the Debian-based upstream Python image.
* Install the MySQL client utilities (including `mysqldump`) using the `mysql-client-8.0` Ubuntu package.
* Bump the MongoDB clients to version 4.4.

Update Dockerfile: use Ubuntu Focal as the base image, install MySQL 8 and MongoDB 4.4 clients

---

CHANGELOG.md
tutorbackup/templates/backup/build/backup/restore_services.py

If we are restoring a large database, the large amount of statements executed my importing a mysqldump may lead to a considerable number of binlog entries. Afterwards, it is usually prudent to have MySQL remove expired binlog files. One way to force MySQL into doing that is to flush logs.
Thus, add a `mysqladmin flush-logs` command right after successfully completing a restore.

fix: Flush logs after MySQL restore

---

CHANGELOG.md
README.md
tutorbackup/patches/k8s-jobs
tutorbackup/plugin.py
tutorbackup/templates/backup/build/backup/backup_services.py
tutorbackup/templates/backup/build/backup/restore_services.py

In certain cloud DB services where it's not possible to lock the DB, the single-transaction option in mysql dumps and flushing logs after restoring will fail. For these cases, you can now set BACKUP_MYSQL_SINGLE_TRANSACTION and BACKUP_MYSQL_FLUSH_LOGS to false. Fixes: #77

feat: Add options to opt-out single-transaction and flush logs in mysql

---

tutorbackup/templates/backup/build/backup/Dockerfile

- Bump MongoDB client repo to Ubuntu Jammy
- Bump MongoDB client repo to version 7.0

Update MongoDB client repo to the one for MongoDB 7.0 and Ubuntu Jammy

---

CHANGELOG.md
README.md
tutorbackup/plugin.py
tutorbackup/templates/backup/build/backup/Dockerfile

Add a config option `BACKUP_BASE_IMAGE` that allows to override the base image for builds.

feat: Allow to override the base image for builds

---

CHANGELOG.md
README.md
tutorbackup/patches/k8s-jobs
tutorbackup/plugin.py
tutorbackup/templates/backup/build/backup/s3_client.py

Include the `request_checksum_calculation` config option to make sure backups can be uploaded to s3 with boto3 >= 1.37.34.

feat: Support latest version of boto3

---

README.md

Add a paragraph to the README that covers how to transfer backups from one location to another, using rclone.

docs: Include rclone in README
